// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Practica.Server.Data;

namespace Practica.Server.Migrations
{
    [DbContext(typeof(ApplicationDataContext))]
    partial class ApplicationDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("Practica.Shared.Entities.Bodega", b =>
                {
                    b.Property<int>("ID_Bodega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Id_Sucursal")
                        .HasColumnType("int");

                    b.Property<string>("NombreBodega")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("SucursalIdSucursal")
                        .HasColumnType("int");

                    b.HasKey("ID_Bodega");

                    b.HasIndex("SucursalIdSucursal");

                    b.ToTable("Bodegas");
                });

            modelBuilder.Entity("Practica.Shared.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id_Ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("NombreCiudad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Ciudad");

                    b.ToTable("Ciudades");

                    b.HasData(
                        new
                        {
                            Id_Ciudad = 1,
                            NombreCiudad = "Antofagasta"
                        },
                        new
                        {
                            Id_Ciudad = 2,
                            NombreCiudad = "Calama"
                        });
                });

            modelBuilder.Entity("Practica.Shared.Entities.Comuna", b =>
                {
                    b.Property<int>("Id_Comuna")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("CiudadId_Ciudad")
                        .HasColumnType("int");

                    b.Property<int>("Id_Ciudad")
                        .HasColumnType("int");

                    b.Property<string>("NombreComuna")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id_Comuna");

                    b.HasIndex("CiudadId_Ciudad");

                    b.ToTable("Comunas");
                });

            modelBuilder.Entity("Practica.Shared.Entities.Sucursal", b =>
                {
                    b.Property<int>("IdSucursal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DireccionSucursal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Id_Comuna")
                        .HasColumnType("int");

                    b.Property<string>("NombreSucursal")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("IdSucursal");

                    b.ToTable("Sucursales");
                });

            modelBuilder.Entity("Practica.Shared.Entities.Bodega", b =>
                {
                    b.HasOne("Practica.Shared.Entities.Sucursal", "Sucursal")
                        .WithMany()
                        .HasForeignKey("SucursalIdSucursal");

                    b.Navigation("Sucursal");
                });

            modelBuilder.Entity("Practica.Shared.Entities.Comuna", b =>
                {
                    b.HasOne("Practica.Shared.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("CiudadId_Ciudad");

                    b.Navigation("Ciudad");
                });
#pragma warning restore 612, 618
        }
    }
}
